if ( $?PHLEX_PLUGIN_PATH ) then
    setenv PHLEX_PLUGIN_PATH_CONDA_BACKUP "$PHLEX_PLUGIN_PATH"
    setenv PHLEX_PLUGIN_PATH "${CONDA_PREFIX}/lib:${PHLEX_PLUGIN_PATH}"
else
    setenv PHLEX_PLUGIN_PATH "${CONDA_PREFIX}/lib"
endif
