if set -q PHLEX_PLUGIN_PATH
    set -gx PHLEX_PLUGIN_PATH_CONDA_BACKUP $PHLEX_PLUGIN_PATH
    set -gx PHLEX_PLUGIN_PATH $CONDA_PREFIX/lib:$PHLEX_PLUGIN_PATH
else
    set -gx PHLEX_PLUGIN_PATH $CONDA_PREFIX/lib
end
