#!/bin/sh
if [ -n "${PHLEX_PLUGIN_PATH_CONDA_BACKUP:-}" ]; then
  export PHLEX_PLUGIN_PATH="${PHLEX_PLUGIN_PATH_CONDA_BACKUP}"
  unset PHLEX_PLUGIN_PATH_CONDA_BACKUP
else
  unset PHLEX_PLUGIN_PATH
fi
